site_name: The Python Guide
repo_url: https://github.com/thepyguide/thepyguide.github.io
repo_name: thepyguide/thepyguide.github.io
copyright: Copyright &copy; 2024 - 2025 Izhar Ahmad

theme:
  name: material
  custom_dir: docs/_templates
  logo: _images/logo_header.png
  favicon: _images/favicon.png
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
      - navigation.footer
      - navigation.instant
      - navigation.indexes
      - navigation.tabs
      - navigation.sections
      - navigation.path
      - content.code.annotate 
      - content.code.copy
      - content.action.edit
      - search.suggest
      - search.highlight
      - search.share
  font:
      text: Ubuntu

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - md_in_html
  - attr_list
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: simple/buymeacoffee
      link: https://www.buymeacoffee.com/izxxr
      name: Donate on BuyMeACoffee

    - icon: simple/kofi
      link: https://ko-fi.com/izxxr
      name: squidfunk on Fosstodon
      name: Donate on Ko-Fi

extra_css:
  - _styles/index.css
  - _styles/home.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - About: about.md
  - Learn Python:
    - introduction.md

    - 1. Getting Started:

      - getting-started/installing-python.md
      - getting-started/python-environments.md
      - getting-started/the-first-program.md

    - 2. Fundamental Concepts:

      - fundamentals/variables-and-data-types.md
      - fundamentals/io-operations.md
      - fundamentals/comments.md
      - fundamentals/mathematical-operations.md
      - fundamentals/dealing-with-errors.md

    - 3. Control Structures:

      - control-structures/conditionals.md
      - control-structures/indentation.md
      - control-structures/logical-operations.md
      - control-structures/conditionals-continued.md
      - control-structures/truth-value.md
      - control-structures/for-loop.md
      - control-structures/while-loop.md
      - control-structures/loop-control.md

    - 4. String Operations:

      - string-operations/indexing-strings.md
      - string-operations/slicing-strings.md
      - string-operations/formatting-strings.md
      - string-operations/string-methods.md
      - string-operations/other-operations.md

    - 5. Functions:

      - functions/functions-basics.md
      - functions/arguments.md
      - functions/return-value.md
      - functions/scopes.md
      - functions/builtin-functions.md
      - functions/lambda-expressions.md

    - 6. Exception Handling:

      - exception-handling/try-except-statements.md
      - exception-handling/else-finally-statements.md
      - exception-handling/pass-statement.md
      - exception-handling/common-errors.md

    - 7. Data Structures:

      - 7.1. Lists:

        - data-structures/lists/introduction.md
        - data-structures/lists/manipulating-elements.md

      - 7.2. Tuples:

        - data-structures/tuples/introduction.md
        - data-structures/tuples/manipulating-elements.md
        - data-structures/tuples/unpacking-tuples.md

      - 7.3. Sets:

        - data-structures/sets/introduction.md
        - data-structures/sets/manipulating-elements.md
        - data-structures/sets/set-operations.md

      - data-structures/sequence-operations.md

      - 7.5. Dictionaries:

        - data-structures/dictionary/introduction.md
        - data-structures/dictionary/accessing-items.md
        - data-structures/dictionary/manipulating-items.md

      - data-structures/copying-data-structures.md

  - Contributor Guide:

      - contributing/index.md
      - contributing/issues.md
      - contributing/pull-requests.md
      - contributing/development.md
